export const AUTH_COPY = {
  requiredEmail: "E-mail é obrigatório.",
  invalidEmail: "E-mail inválido.",
  requiredPassword: "Senha é obrigatória.",
  invalidPassword: "A senha deve ter pelo menos 8 caracteres.",
  requiredConfirmPassword: "Confirmação de senha é obrigatória.",
  passwordMismatch: "As senhas não coincidem.",
  invalidForm: "Revise os campos informados.",
  invalidCredentials: "E-mail ou senha inválidos.",
  genericAuthError: "Não foi possível autenticar agora. Tente novamente.",
  signupDisabled: "A conta do proprietário já foi criada. Faça login para continuar.",
  emailInUse: "Este e-mail já está em uso.",
  noOwnerAccount: "Ainda não existe uma conta cadastrada.",
  signupSuccess: "Conta criada com sucesso. Faça login para continuar.",
} as const;
